lab3_4/project/books/urls.py
from django.urls import path, re_path
from . import views

app_name="books"
urlpatterns = [
    path("", views.BookListView.as_view(), name="books"),
    path("<int:pk>/", views.BookDetailView.as_view(), name="book_detail"),
    path("<int:book_id>/vote/", views.vote, name="vote"),
    path("favorites/", views.FavoriteBooksView.as_view(), name="favorites"),
    # re_path(r"search\?q=(?P<quiery_string>[0-9A-Za-z]+)?$", views.search, name='search'),
    re_path(r"^search/$", views.search, name='search'),
    # path("search?q=<str:quiery_string>)", views.search, name='search'),
]

urlpatterns+=[
    path("authors/", views.AuthorListView.as_view(), name="authors"),
    path("authors/<int:pk>/", views.AuthorDetailView.as_view(), name="author-details"),
    path("genres/", views.GenresListView.as_view(), name="genres"),
    path("genres/<int:pk>/", views.GenreDetailView.as_view(), name="genre-details"),
]

lab3_4/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("books/", include("books.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab3_4/project/books/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_of_birth = models.DateField(null=True, blank=True)

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])


    def __str__(self):
        """String for representing the Model object."""
        return '{0}, {1}'.format(self.last_name, self.first_name)


class Genre(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self) -> str:
        return self.name


# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, null=True, on_delete=models.SET_NULL)
    genre = models.ManyToManyField(Genre)
    publish_date = models.DateTimeField("publish date")
    favorite_of = models.ManyToManyField(settings.AUTH_USER_MODEL)

    def __str__(self) -> str:
        return f"{self.title}"
    

    def get_genre(self):
        return ", ".join(genre_.name for genre_ in self.genre.all())


    def get_favorite(self):
        return ", ".join(fav.first_name for fav in self.favorite_of.all())

# class User(models.Mode)

lab3_4/project/books/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpRequest, Http404, HttpResponseRedirect
from .models import Book, Genre, Author
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.decorators.csrf import csrf_protect

# Create your views here.
class BookListView(generic.ListView):
    template_name = "books/index.html"
    context_object_name = "books_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Book.objects.order_by("-publish_date")
    

class AuthorListView(generic.ListView):
    template_name = "books/author_list.html"
    context_object_name = "author_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Author.objects.order_by("-date_of_birth")
    

class GenresListView(generic.ListView):
    template_name = "books/genre_list.html"
    context_object_name = "genre_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Genre.objects.all()

 
class FavoriteBooksView(LoginRequiredMixin, generic.ListView):
    template_name = "books/index.html"
    context_object_name = "books_list"
    model = Book

    def get_queryset(self) -> QuerySet[Any]:
        return Book.objects.filter(favorite_of=self.request.user)
    

# class GenreBooksView(generic.ListView):
#     template_name = "books/favorite.html"
#     model = Book

#     def get_queryset(self) -> QuerySet[Any]:
#         return Book.objects.filter(genre=self.request.user)


class BookDetailView(generic.DetailView):
    model = Book
    template_name = "books/book_detail.html"


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = "books/author_detail.html"


class GenreDetailView(generic.DetailView):
    model = Genre
    template_name = "books/genre_detail.html"

@csrf_protect
@login_required
def vote(request, book_id):
    if request.method == 'POST':
        book = get_object_or_404(Book, pk=book_id)
        if request.POST.get("Add_fav")== "Add to favorites":
            book.favorite_of.add(request.user)
            book.save()
            return HttpResponseRedirect(reverse("books:book_detail", args=(book.id,)))
        
        elif request.POST.get("return")== "back":
            # return HttpResponseRedirect(reverse("", args=(book.id,)))
            return HttpResponseRedirect("/books")

# https://django.cowhite.com/blog/working-with-url-get-post-parameters-in-django/
def search(request):

    if request.method == "GET":
        quiery_string = request.GET['q']
        print(quiery_string)
        books = Book.objects.filter(
            Q(title__icontains=quiery_string) |
            Q(author__first_name__icontains=quiery_string) #|
            # Q(genre__icontains=quiery_string)
        ).order_by('-publish_date')

        context = {'books': books}

        return render(request, 'books/search.html', context)


        # authors = Author.objects.filter(

        # )

lab3_4/project/books/templates/books/author_detail.html
{% extends 'books/base_template.html' %}

{% block content %}

    <legend><h2>{{ author.first_name }} {{ author.last_name }}</h2></legend>
    <p>Date of birth: {{ author.date_of_birth }} </p>
    <h3>Books</h3>
    <nav>
        <ul>
            {% for book in author.book_set.all %}
            <dt><a href="{% url 'books:vote' book.pk %}">{{book.title}}</a></dt>
            {% endfor %}
        </ul>
    </nav>
    <dl>
</dl>

{% endblock %}

lab3_4/project/books/templates/books/author_list.html
{% extends 'books/base_template.html' %}

{% block content %}

    {% if author_list %}
        <head>Authors</head>
        <ul>
            {% for author in author_list %}
                <li><a href="/books/authors/{{author.id}}">{{ author.first_name }} {{ author.last_name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No books are available.</p>
    {% endif %}

{% endblock %}

lab3_4/project/books/templates/books/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="container-fluid">

<div class="row">
  <div class="col-sm-2">
  {% block sidebar %}
  
 
    <ul class="sidebar-nav">
      <li>User: {{ user.get_username }}</li>
      <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
    </ul>
  
    <hr>
      <ul class="sidebar-nav">
        <li><a href="/books/">Books</a></li>
        <li><a href="/books/genres/">Genres</a></li>
        <li><a href="/books/authors/">Authors</a></li>
      </ul>
    </hr>

    <hr>
      <ul class="sidebar-nav">
        <li><a href="/books/favorites/">Favorite</a></li>
      </ul>
    </hr>

  {% endblock %}
  </div>

  <div class="col-sm-10 ">
    <div class="search-container">
      <form action="/books/search">
        <input type="text" placeholder="Search" name="q">
        <button type="submit">Submit</button>
      </form>
    </div>

  {% block content %}{% endblock %}
  
  {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %} 
  
  
  </div>
</div>

</div>
</body>
</html>

lab3_4/project/books/templates/books/book_detail.html
{% extends 'books/base_template.html' %}

{% block content %}

    <form action="{% url 'books:vote' book.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ book.title }}</h1></legend>
            <p>Author: {{ book.author }}</p>
            <p>Release: {{ book.publish_date }}</p>
            <p>Genre: {{ book.genre }}</p>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        </fieldset>
        <input class="favorite styled" type="submit" value="Add to favorites" name="Add_fav" />
        <input class="favorite styled" type="submit" value="back" name="return" />
    </form>

{% endblock %}

lab3_4/project/books/templates/books/genre_detail.html
{% extends 'books/base_template.html' %}

{% block content %}

    <legend><h2>{{ genre.name }}</h2></legend>
    <h3>Books</h3>
    <nav>
        <ul>
            {% for book in genre.book_set.all %}
            <dt><a href="{% url 'books:vote' book.pk %}">{{book.title}}</a></dt>
            {% endfor %}
        </ul>
    </nav>
    <dl>
    </dl>

{% endblock %}

lab3_4/project/books/templates/books/genre_list.html
{% extends 'books/base_template.html' %}

{% block content %}

    {% if genre_list %}
        <head>Genres</head>
        <ul>
            {% for genre in genre_list %}
                <li><a href="/books/genres/{{genre.id}}">{{ genre.name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No books are available.</p>
    {% endif %}

{% endblock %}

lab3_4/project/books/templates/books/index.html
{% extends 'books/base_template.html' %}

{% block content %}

    {% if books_list %}
        {% csrf_token %}
        {% for book in books_list %}
            <li><a href="/books/{{ book.id }}/">{{ book.title }}</a></li>
        {% endfor %}
    {% else %}
        <p>No books are available.</p>
    {% endif %}

{% endblock %}

lab3_4/project/books/templates/books/search.html
{% extends 'books/base_template.html' %}

{% block content %}

    {% if books %}
        <head>Books</head>
        {% csrf_token %}
        {% for book in books %}
            <li><a href="/books/{{ book.id }}/">{{ book.title }}</a></li>
        {% endfor %}
    {% else %}
        <p>No books are available.</p>
    {% endif %}

{% endblock %}